var app = angular.module('BAC', []);

app.controller('cards', function($scope, $interval) {
  var cardQuestions = ["During meetings I like to think about _____. ",
    "I have to be honest, what really gets me going is _____.",
    "Eww is that _____ on your desk? ",
    "I got in trouble when I accidentally tweeted a picture of _____ from the company account.",
    "If you're going on a date, always remember to bring _____.",
    "Can you work late tonight? I want to show you _____.",
    "Lovin' you is easy 'cause you're _____.",
    "Let's use _____ to make this really sticky.",
    "I want _____ by EOD.",
    "Spice up your nightlife with  _____.",
    "_____ always makes a conference more exciting!",
    "_____ ended my last relationship.",
    "What never fails to liven up the party?",
    "When I'm alone, I'm always _____.",
    "What will always get you a promotion?",
    "Deliver the best user experience with _____.",
    "I was late for work because I was _____.",
    "It's a pity millennials only care about _____.",
    "How did _____ get in here!?!",
    "_____ always makes a better brand.",
  ];
  var cardAnswers = ["A 300 word CTA.",
    "Unexpected market penetration.",
    "My conversion rate.",
    "Expanding your dropdown.",
    "Sensitive touchpoints.",
    "Debriefing in the conference room.",
    "Dat SaaS.",
    "A robust front-end.",
    "Back-end integration.",
    "Widening the sales funnel.",
    "Millennials.",
    "Vigorous inbound marketing.",
    "Mad prospecting skills.",
    "Indecent marketing exposure.",
    "Going below the fold.",
    "Making a hot spot.",
    "Whiteboarding torture.",
    "Aggressively growth hacking.",
    "Pitching a great deck.",
    "My widget. ",
    "3D touching.",
    "An epic toolkit.",
    "Unprotected source code. ",
    "A drip campaign.",
    "Seven Ps.",
    "Slippage.",
    "Paid placement. ",
    "Opting in.",
    "Scrolljacking. ",
    "A pop up.",
    "A soft launch.",
    "Max-width.",
    "Pulling my repo.",
    "The ol' finger protocol.",
    "Some peer-to-peer action.",
    "Bundling your pricing structure. ",
    "A sexy cross-platform app.",
    "A floppy disk.",
    "The bounce rate.",
    "Stickiness.",
    "Flooding my pipeline.",
    "Bricks n' Clicks.",
    "Swiping right.",
    "DINKs (double income, no kids).",
    "An email blast.",
    "Version control.",
    "A really bad hashtag.",
    "His SPAM filter.",
    "Stuffing keywords. ",
    "Crawling your pages.",
    "Data linkage.",
    "Cookies.",
    "An overflowing inbox.",
    "Prospecting hot leads.",
    "Deep linking.",
    "A massive spreadsheet.",
    "Clickbait. ",
    "An epic toolkit.",
    "The sloppy code.",
    "A unicorn.",
    "Servicing your clients.",
    "Bulk packaging.",
    "A firm deadline.",
    "The CEO.",
    "User seats. ",
    "An asynchronous hookup. ",
    "A dongle. ",
  ];
  $scope.currentQuestion = cardQuestions[Math.floor(Math.random() * cardQuestions.length)];
  $scope.currentAnswer = cardAnswers[Math.floor(Math.random() * cardAnswers.length)];

  $interval(function() {
    $scope.currentQuestion = cardQuestions[Math.floor(Math.random() * cardQuestions.length)];
  }, 16000)

  $interval(function() {
    $scope.currentAnswer = cardAnswers[Math.floor(Math.random() * cardAnswers.length)];
  }, 4000)

  
})